name: ATS CI/CD Pipeline   # Pipeline ka naam (Actions tab me dikhega)

on:                       # Kab chale
  push:
    branches: [ "main" ]  # jab main branch me push hoga
  pull_request:
    branches: [ "main" ]  # jab PR banega main branch pe

jobs:                     # Kaam ke groups
  build:                  # Ek job "build" naam se
    runs-on: ubuntu-latest # Ubuntu server pe chalega

    steps:                # Kaam ke steps
    - name: Checkout Repository
      uses: actions/checkout@v3   # repo ka code checkout karega

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2   # docker ready karega

    - name: Build Docker Image
      run: docker build -t ats-system:latest .  # docker image build karega

    - name: Run Docker Container
      run: docker run -d -p 8000:8000 -p 8501:8501 ats-system:latest  # container run karega
